version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: vue-practice-api
    entrypoint: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - ./api:/api:cached
      - bundle:/usr/local/bundle:cached
      # exclude volumes
      - /api/vendor
      - /api/tmp
      - /api/log
      - /api/.git

  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    container_name: vue-practice-front
    entrypoint: yarn serve
    depends_on:
      - api
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./api/public:/public:delegated
      - ./front:/front:cached
      - ./front/node_modules:/front/node_modules:delegated
      - yarn_cache:/usr/local/share/.cache/yarn/v6:cached # `yarn cache dir`

  e2e:
    build:
      context: .
      dockerfile: ./docker/cypress/Dockerfile
    container_name: vue-practice-cypress
    command: yarn test:e2e
    depends_on:
      - front
    environment:
      - CYPRESS_baseUrl=http://front
    volumes:
      - ./front:/cypress:cached
      # exclude volumes
      - /cypress/node_modules

  vue3:
    build:
      context: .
      dockerfile: ./docker/vue3/Dockerfile
    container_name: vue-practice-vue3
    entrypoint: yarn serve
    depends_on:
      - api
    ports:
      - 8888:8888
    volumes:
      - ./vue3:/vue3:cached
      - yarn_cache2:/usr/local/share/.cache/yarn/v6:cached # `yarn cache dir`
      # exclude volumes
      - /vue3/node_modules

volumes:
  bundle:
  yarn_cache:
  yarn_cache2:
