import '@/plugins/axios'
import '@/plugins/bootstrap'
import '@/plugins/composition-api'
import '@/plugins/element-ui'
import '@/plugins/loading'
import '@/plugins/ls'
import '@/plugins/toastrs'
import '@/plugins/vue-js-modal'
